### ISSUE TITLE
time series

### ISSUE THREAD

**Issue by Winthan** [mindsdb/mindsdb-examples#23]
When I am trying to use time series, it is having a problem, I tried adding",", end of each object as well, it is not working for some reasons. Spyder is showing invalid syntax. 
```

import mindsdb
import pandas as pd

mdb = mindsdb.Predictor(name="ES-price")

mdb.learn(
    from_data="ES.csv",  
    to_predict='close',
    timeseries_settings = {
      order_by: ['timestamp']
      nr_predictions: 3
      use_previous_target: True 
      window: 100
    }
)
```
   **nr_predictions: 3
    ^**
SyntaxError: invalid syntax

How can I create a time series prediction with mindsdb? 

If I use only order_by, it is saying order_by is not defined at all. 
````
mdb.learn(
    from_data="ES.csv",  
    to_predict='close',
    timeseries_settings = {
    order_by: ['timestamp']
      
    }
)

```

**order_by: ['timestamp']

NameError: name 'order_by' is not defined**

**Comment by ZoranPandovski** [comment]
Answered in mindsdb. The problem was in the wrong syntax.
